Revert "on7: Enable lte"
This reverts commit 5eff6f6162b55cd5b51ef2a8aa02752384bf7fc4.

device/samsung/o7prolte/init/init_o7prolte.cpp:40:48: error: use of undeclared identifier 'default_network'
         property_set("ro.telephony.default_network", default_network);
error :(